### ISSUE TITLE
run my own mesh 

### ISSUE THREAD

**Issue by ziyeshanwai** [SuwoongHeo/Deformation-Transfer-Matlab#1]
hello, when i run your code using my own mesh data, i get follow error:
The logical indices in position 1 contain a true value outside of the array bounds.

Error in build_phase1 (line 60)
                    -val2(constid(2,:)>0,:)' .* VT4(marker(marker==U2(constid(2,:)>0),2),k)';

Error in non_rigid_registration (line 76)
[M C] = build_phase1(Adj_idx, E, FS4, VT4, ws, wi, marker);

Error in demo (line 24)
[ VS_Reg, VT_Reg, S_factor,T_factor] = non_rigid_registration(VS, FS, VT, FT, 1.0, 0.01, [1 500 3000 5000], marker, 'DF_reg_phase2.mat');
i 'm sure that i have marked the correct markpoints

**Comment by icech** [comment]
I also encounter this problem. Since someone may also  face this problem, i add this comment.  The reason is the mark index in this code is different from maya or blender. You need to add a line 'marker = marker + 1' to match them in the demo.m.
